### ISSUE TITLE
Docker (Compose) deployment options?

### ISSUE THREAD

**Issue by iBug** [codidact/qpixel#70]
Not much detail needed, I believe `:)`

Wrapping this software up in a Docker container will surely make development, testing and deployment easier. At first glance, three containers are required: a Redis, a MySQL, and the last one for this app itself.

The Dockerfile would be pretty straightforward: Install necessary software from APT repository and RubyGems, then `ENTRYPOINT /usr/src/app/bin/rails`. A custom script to initialize the application by reading environment variables and generating the configuration files at the first start is also in need.

With all those stuff ready, a `docker-compose.yml` should be easy to work out.

The [`Dockerfile` file](https://github.com/Charcoal-SE/metasmoke/blob/master/Dockerfile) from Charcoal-SE/metasmoke would be a good point to start at, although it's missing some best-practices for Docker.

Ideas?

**Comment by ArtOfCode-** [comment]
Eh... I don't like Docker, personally, so I'd still deploy the manual way, meaning unless someone else was using it, the Dockerfile would end up being outdated and unmaintained. If others would find it useful then we might want to do this, but if nobody's going to use it there's probably little point.

**Comment by vsoch** [comment]
I want to add support for Docker, it's the bread and butter to quick deployment on the cloud these days. It's also hugely useful to quickly bring up a development environment without mucking around with your host.

**Comment by cellio** [comment]
Given the previous comment, I don't see the harm in reopening this and waiting for someone who wants to work on it.  It doesn't constrain the codidact.com deployment; it's just an option, right?

**Comment by vsoch** [comment]
Exactly! +1 for re-opening, and if no one grabs this quickly, I can definitely do it.  For some background of my use case (and interest) my group had tried creating a Stack Exchange and didn't make it through the final rounds. We ported to Discourse, but it's not really intended to be akin to a Stack Exchange (even with the voting plugin). Glancing over the deployments here, this seems closer to what my group had in mind to either, so I'm definitely eager to try it out (and in the process, Dockerize).

**Comment by ArtOfCode-** [comment]
Works for me. All yours if you want it, @vsoch :)

**Comment by ArtOfCode-** [comment]
What did the `User.create` call return? That might help tell you something. The usual way of doing this is to create an account with the web interface, then upgrade it from the console, so I'm not well versed in the best way to do it all from a console.

**Comment by vsoch** [comment]
It's the error I showed above about sending the email - here is the full command and result so you can see it. It looks like that error rolls it back?

```rails
irb(main):002:0> User.create(username: "username", password:  Digest::SHA1.hexdigest("username"), email: "username@domain.com", is_global_admin: true, is_global_moderator: true, staff: true)
   (0.2ms)  BEGIN
  User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'username@domain.com' LIMIT 1
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'AdminBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'ModBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  User Create (0.2ms)  INSERT INTO `users` (`email`, `encrypted_password`, `created_at`, `updated_at`, `is_global_moderator`, `is_global_admin`, `username`, `confirmation_token`, `confirmation_sent_at`, `staff`) VALUES ('username@domain.com', '$2a$11$kJX2B/pPlRJfRHM0mszSPu00UyNmyOoJmzdZ3hlg5E.Ez2blGDEcO', '2020-08-23 20:48:25', '2020-08-23 20:48:25', TRUE, TRUE, 'username', '84QfCbEqQSCNyKiBxzwM', '2020-08-23 20:48:25', TRUE)
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'SiteName' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
   (10.5ms)  ROLLBACK
Traceback (most recent call last):
        4: from (irb):2
        3: from (irb):2:in `rescue in irb_binding'
        2: from app/models/user.rb:195:in `send_welcome_tour_message'
        1: from app/models/user.rb:195:in `+'
TypeError (no implicit conversion of nil into String)

```

**Comment by vsoch** [comment]
The user is supposedly created but it's id is nil.

**Comment by ArtOfCode-** [comment]
Sorry I haven't got back to this sooner, the last couple days have been super busy.

If you call `create` and the result has `id: nil`, there were validation or SQL errors while creating it - try running `u = User.create(...)`, then `u.errors.full_messages` - that should reveal any validation errors.

**Comment by vsoch** [comment]
It was the weekend! Totally no worries. And ha, this message!

```
irb(main):002:0> u.errors.full_messages
=> ["Password is too short (minimum is 6 characters)"]
```
Now when I address that and make it >6 characters, I see that rollback error again, because the welcome email cannot be sent.

```
u = User.create(username: "noo", password:"naaaaaa", email: "noo@a.com", is_global_admin: true, is_global_moderator: true, staff: true)
   (0.2ms)  BEGIN
  User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'noo@a.com' LIMIT 1
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'AdminBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'ModBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  User Create (0.2ms)  INSERT INTO `users` (`email`, `encrypted_password`, `created_at`, `updated_at`, `is_global_moderator`, `is_global_admin`, `username`, `confirmation_token`, `confirmation_sent_at`, `staff`) VALUES ('noo@a.com', '$2a$11$RDkeuIvW4Izez8KkQKenV.LkeiPWlXgLXQyjI49N17T2PFw60u3/O', '2020-08-25 18:05:04', '2020-08-25 18:05:04', TRUE, TRUE, 'noo', '1xySKS-uiccs39qQfzf3', '2020-08-25 18:05:04', TRUE)
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'SiteName' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
   (1.0ms)  ROLLBACK
Traceback (most recent call last):
        3: from (irb):5
        2: from app/models/user.rb:195:in `send_welcome_tour_message'
        1: from app/models/user.rb:195:in `+'
TypeError (no implicit conversion of nil into String)
```
There isn't any new insight to look at the errors again because we don't return a new user object. Is there a way to either fix this welcome message functionality, or disable it?

**Comment by vsoch** [comment]
Where are the SiteSettings defined? I think the issue might be that one of them is nil.

**Comment by vsoch** [comment]
The error is about converting nil to a string, but the string in question isn't related to the user, I think it's a SiteSetting? Here is the error:

```
uwsgi_1  | /code/app/models/user.rb:195:in `+': no implicit conversion of nil into String (TypeError)
uwsgi_1  | 	from /code/app/models/user.rb:195:in `send_welcome_tour_message'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:517:in `block in invoke_after'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:517:in `each'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:517:in `invoke_after'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:133:in `run_callbacks'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/callbacks.rb:346:in `_create_record'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/timestamp.rb:102:in `_create_record'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:705:in `create_or_update'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/callbacks.rb:342:in `block in create_or_update'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/callbacks.rb:342:in `create_or_update'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:275:in `save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:46:in `save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
uwsgi_1  | 	from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:310:in `block in save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:309:in `save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/suppressor.rb:44:in `save'
uwsgi_1  | 	from /usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:36:in `create'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `<main>'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `eval'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands/runner/runner_command.rb:41:in `perform'
uwsgi_1  | 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
uwsgi_1  | 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
uwsgi_1  | 	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
uwsgi_1  | 	from /usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
uwsgi_1  | 	from /code/bin/rails:9:in `<top (required)>'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
uwsgi_1  | 	from /usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
uwsgi_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
uwsgi_1  | 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
uwsgi_1  | 	from -e:1:in `<main>'
```
and here is the notification attempt:

```ruby
  def send_welcome_tour_message
    return if id == -1

    create_notification('👋 Welcome to ' + SiteSetting['SiteName'] + '! Take our tour to find out ' \
                        'how this site works.', '/tour')
  end
```
So I wonder how SiteName is set?

**Comment by luap42** [comment]
Nah. The issue is, that there is no community here, because you're not on a request. Try going to the mentioned function and replacing `SiteSetting['SiteName']` with `(SiteSetting['SiteName'] || 'Codidact')`.

**Comment by vsoch** [comment]
Gotcha! Cool that I caught the issue :)

**Comment by vsoch** [comment]
Making progress! Now we get through that bug, and there is another issue that the community doesn't have an id:
```
u = User.create(username: "...", password:"...", email: "...", is_global_admin: true, is_global_moderator: true, staff: true)
   (0.8ms)  SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.2ms)  BEGIN
  User Exists (0.4ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'pancakes@a.com' LIMIT 1
  SiteSetting Load (0.4ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'AdminBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  SiteSetting Load (0.2ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'ModBadgeCharacter' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  User Create (0.4ms)  INSERT INTO `users` (`email`, `encrypted_password`, `created_at`, `updated_at`, `is_global_moderator`, `is_global_admin`, `username`, `confirmation_token`, `confirmation_sent_at`, `staff`) VALUES ('pancakes@a.com', '$2a$11$t0LCKRfKjjW1eGkweB3bdeV1A45RZGBGKBmHKXivgyRl3kFvbxZpm', '2020-08-25 18:14:58', '2020-08-25 18:14:58', TRUE, TRUE, 'vanessa', 'bYYgC87gZRQzB3e5VgxG', '2020-08-25 18:14:58', TRUE)
  SiteSetting Load (0.3ms)  SELECT  `site_settings`.* FROM `site_settings` WHERE `site_settings`.`community_id` IS NULL AND `site_settings`.`name` = 'SiteName' ORDER BY IF(site_settings.community_id IS NULL, 1, 0) LIMIT 1
  Notification Create (0.9ms)  INSERT INTO `notifications` (`content`, `link`, `created_at`, `updated_at`) VALUES ('👋 Welcome to Codidact! Take our tour to find out how this site works.', '/tour', '2020-08-25 18:14:58', '2020-08-25 18:14:58')
   (3.8ms)  ROLLBACK
Traceback (most recent call last):
        3: from (irb):1
        2: from app/models/user.rb:195:in `send_welcome_tour_message'
        1: from app/models/user.rb:70:in `create_notification'
ActiveRecord::NotNullViolation (Mysql2::Error: Field 'community_id' doesn't have a default value: INSERT INTO `notifications` (`content`, `link`, `created_at`, `updated_at`) VALUES ('👋 Welcome to Codidact! Take our tour to find out how this site works.', '/tour', '2020-08-25 18:14:58', '2020-08-25 18:14:58'))
```
and the function
```
  def create_notification(content, link)
    notification = Notification.create(content: content, link: link)
    notifications << notification
  end
```
Is Codadict designed to be connected to some larger community, and then get an id?

**Comment by luap42** [comment]
Ah. Good that we ruled that option out. :D Okay. Revert the change and add ` || RequestContext.community.nil?` to the end of the return-clause at the top. That could work. :)

**Comment by vsoch** [comment]
That worked! There was a tiny issue with wanting to send an email, but the user seems to have been created okay anyway :)

```
...
   (1.9ms)  COMMIT
Devise::Mailer#confirmation_instructions: processed outbound mail in 4.6ms
Traceback (most recent call last):
        1: from (irb):1
ArgumentError (No :access_key_id provided)
```
But I can at least get acknowledgement from the interface that my account exists! 

![image](https://user-images.githubusercontent.com/814322/91213527-f8338980-e6ce-11ea-9688-2f2a5128b347.png)

It looks like you are using something called Devise, and there is @ArtOfCode- UK email address and a key (but still the error because no access key?) So I think we would either need to get that working, or to have an option to disable email confirmation (likely would be useful for more development / Docker setups).

**Comment by vsoch** [comment]
This might be promising
```
  # ==> Configuration for :confirmable
  # A period that the user is allowed to access the website even without
  # confirming their account. For instance, if set to 2.days, the user will be
  # able to access the website for two days without confirming their account,
  # access will be blocked just in the third day. Default is 0.days, meaning
  # the user cannot access the website without confirming their account.
  # config.allow_unconfirmed_access_for = 2.days
```

**Comment by luap42** [comment]
Yeah. That issue is known and happens, because no email is configured. As we require validation, it's also IMO status-bydesign.

You can update the user by setting confirmed_at to the current time. Something like `user.update confirmed_at: DateTime.now` should work for the initial user setup.

**Comment by vsoch** [comment]
Success! 

![image](https://user-images.githubusercontent.com/814322/91217274-79414f80-e6d4-11ea-99e9-fee7d4df9e0d.png)

So I'm logged in, and wondering what kinds of other actions an admin needs to do for setup? For example, when I try to create a post I get an error about tag sets not having a default value.

![image](https://user-images.githubusercontent.com/814322/91217426-b7d70a00-e6d4-11ea-95c2-e298d0863cfd.png)

The function being called is this one in post.rb

```
  def update_tag_associations
    tags_cache.each do |tag_name|
      tag = Tag.find_or_create_by name: tag_name, tag_set: category.tag_set
      unless tags.include? tag
        tags << tag
      end
    end
    tags.each do |tag|
      unless tags_cache.include? tag.name
        tags.delete tag
      end
    end
  end
```
with parent in posts_controller.rb - seems like the error is on @post.save (line 29)

```
  def create
    @category = Category.find(params[:category_id])
    @post = Post.new(post_params.merge(category: @category, user: current_user,
                                       post_type_id: params[:post][:post_type_id] || params[:post_type_id],
                                       body: helpers.render_markdown(params[:post][:body_markdown])))

    if @category.min_trust_level.present? && @category.min_trust_level > current_user.trust_level
      @post.errors.add(:base, "You don't have a high enough trust level to post in the #{@category.name} category.")
      render :new, status: 403
      return
    end

    if @post.save
      redirect_to helpers.generic_show_link(@post)
    else
      render :new, status: 400
    end
  end
```

**Comment by luap42** [comment]
Heh. I thought @ArtOfCode- had written something about that, but it was on a different post. :D

You need to go to the categories, edit them and choose a tag set (likely Main for Q&A and Meta for Meta). You might also want to go to /admin/setup to do some administrative setup stuff, including seeding tags.

**Comment by vsoch** [comment]
I probably just missed it! Let me give those areas a quick look.

**Comment by vsoch** [comment]
Yep that worked!

**Comment by vsoch** [comment]
okay things are looking good, I've tested it again from start to finish, and works! I'm going to open a PR to discuss changes. This version is done for development, so likely in the PR we'd want to discuss how the user can set an environment variable for the docker-compose that would signal production. But if we do that, we'd also want to make sure the emails will work. It would also be okay to have this first PR provide the container build for development only. I'll repeat this when I open the PR.

**Comment by sbkg0002** [comment]
Is it me, or is this still an issue when https://github.com/codidact/qpixel/blob/develop/docker/README.md is followed? I still got this with Docker for Mac:

![img](https://user-images.githubusercontent.com/814322/90966412-55d99300-e48f-11ea-86b3-edafe15ff22b.png)

**Comment by ArtOfCode-** [comment]
@sbkg0002 You need to change the community record in the database to have a host field of `0.0.0.0:3000`, then it'll work

**Comment by mattjbrent** [comment]
@sbkg0002 did you try using localhost instead of 0.0.0.0 meta address?

**Comment by sbkg0002** [comment]
Thanks @artofcode-, but how?
