### ISSUE TITLE
Puma caught this error: undefined method `id' for nil:NilClass (NoMethodError) - Home Page

### ISSUE THREAD

**Issue by arvi9** [codidact/qpixel#794]
Puma caught this error: undefined method `id' for nil:NilClass (NoMethodError)
/code/app/controllers/categories_controller.rb:171:in `update_last_visit'
/code/app/controllers/categories_controller.rb:24:in `homepage'

**Comment by cellio** [comment]
I'm guessing on the component; @ArtOfCode- can you review and correct if needed?

**Comment by Oaphi** [comment]
Note in case this gets lost: this happens when trying to visit the "homepage" when no homepage category exists.
